In [1]:
import numpy as np
import os

from utils.plot_utils import *
from utils.mesh_utils import *
from utils.file_utils import *
from basis.lagrange import *

In [2]:
# Define the reference triangle
triangle_vertices = np.array([[0, 0], [1, 0], [0, 1]])

In [3]:
# Construct W
W = np.array([linear_triangle_basis(x, y) for x, y in triangle_vertices])

print("W shape:", W.shape)
print("W:")
print(W)

W shape: (3, 3)
W:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [9]:
save_folder = '2d-tri'
save_path = os.path.join('/Users/liujunyu/Desktop/Research/UVic_NYU/IGA_IPC/code/polyfem/experiments/mesh/ipc', save_folder)
if not os.path.exists(save_path):
    os.makedirs(save_path)

# Currently hardcode for debug
tri_edges = [[0, 1], [1, 2], [2, 1]]
tri_faces = [[0, 1, 2]]
# save_mapping_to_hdf5(W, tri_edges, tri_faces, os.path.join(save_path, '2d-tri-map.hdf5'))
path = os.path.join(save_path, '2d-tri-map.hdf5')
save_weights(path, W, n_fem_vertices=3, vertices=triangle_vertices, edges=tri_edges, faces=tri_faces)
                 