In [1]:
import os
import h5py

In [2]:
map_foldername = '2d-quad'
map_folder = os.path.join('/Users/liujunyu/Desktop/Research/UVic_NYU/IGA_IPC/code/polyfem/experiments/mesh/iga-ipc', map_foldername)
map_filename = '2d-quad-map.hdf5'
map_filepath = os.path.join(map_folder, map_filename)

reference_map_filename = 'triangle_ref1-P2.hdf5'
reference_map_folder = '/Users/liujunyu/Desktop/Research/UVic_NYU/IGA_IPC/code/polyfem/experiments/high-order-ipc-data/weights/higher_order'
reference_map_filepath = os.path.join(reference_map_folder, reference_map_filename)

printed based on:

```Attributes of /: {}
Attributes of //ordered_edges: {}
Attributes of //ordered_faces: {}
Attributes of //weight_triplets: {'shape': array([54, 15])}
Attributes of //weight_triplets/cols: {}
Attributes of //weight_triplets/rows: {}
Attributes of //weight_triplets/values: {}```

In [12]:
import h5py
import numpy as np

def print_dataset(f, name):
    try:
        data = f[name][:]
        print(f"{name}:")
        if isinstance(data, np.ndarray) and data.size > 100:
            print(f"Shape: {data.shape}")
            print("First few elements:")
            print(data.flatten()[:100])  # Print first 100 elements
        else:
            print(data)
        print()
    except Exception as e:
        print(f"Error reading {name}: {str(e)}")
        print()

# Open the HDF5 file
with h5py.File(map_filepath, 'r') as f:
    print_dataset(f, '/ordered_edges')
    print_dataset(f, '/ordered_faces')
    print_dataset(f, '/weight_triplets')
    print_dataset(f, '/weight_triplets/cols')
    print_dataset(f, '/weight_triplets/rows')
    print_dataset(f, '/weight_triplets/values')

    # Print the shape attribute of weight_triplets
    print("Shape of weight_triplets:")
    print(f['/weight_triplets'].attrs['shape'])

/ordered_edges:
[[0 1]
 [1 2]
 [2 3]
 [3 1]]

/ordered_faces:
[[0 1 2 3]]

Error reading /weight_triplets: Accessing a group is done with bytes or str, not <class 'slice'>

/weight_triplets/cols:
[0 2 1 3]

/weight_triplets/rows:
[0 1 2 3]

/weight_triplets/values:
[1. 1. 1. 1.]

Shape of weight_triplets:
[4 4]
